name: update
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install cog requests
      - name: Rebuild readme
        run: |
          which python
          pip list
          ls /opt/hostedtoolcache
