name: update
on:
  push:
  schedule:
    - cron: '8 0 * * *' 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Install dependencies
        run: |
          pip install cogapp requests
      - name: Regenerate readme
        run: |
          cog -o README.md -d src/README.md
      - name: Commit and push to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
